### ISSUE TITLE
TypeError: Cannot set property 'LRUCache' of undefined

### ISSUE THREAD

**Issue by davidxmoody** [prismicio/javascript-kit#86]
Updated to version 1.1.6 and getting the following error. Reverting to 1.1.4 fixes the problem. 

I'm *really* sorry I can't be of more help right now but we are about to launch our new website and I'm a little bit busy :)

```
error	03-Jun-2015 15:44:19	TypeError: Cannot set property 'LRUCache' of undefined
error	03-Jun-2015 15:44:19	  at /home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/prismic.io/dist/prismic.io.js:274:25
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/prismic.io/dist/prismic.io.js:277:2)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.gnodeJsExtensionCompiler [as .js] (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/metalsmith/node_modules/gnode/index.js:61:10)
error	03-Jun-2015 15:44:19	  at Module.load (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
error	03-Jun-2015 15:44:19	  at Function.Module._load (module.js:312:12)
error	03-Jun-2015 15:44:19	  at Module.require (module.js:364:17)
error	03-Jun-2015 15:44:19	  at require (module.js:380:17)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/fetch-prismic/get-api.coffee:1:13)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/fetch-prismic/get-api.coffee:1:1)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.loadFile (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
error	03-Jun-2015 15:44:19	  at Module.load (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
error	03-Jun-2015 15:44:19	  at Function.Module._load (module.js:312:12)
error	03-Jun-2015 15:44:19	  at Module.require (module.js:364:17)
error	03-Jun-2015 15:44:19	  at require (module.js:380:17)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/fetch-prismic/index.coffee:2:10)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/fetch-prismic/index.coffee:1:1)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.loadFile (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
error	03-Jun-2015 15:44:19	  at Module.load (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
error	03-Jun-2015 15:44:19	  at Function.Module._load (module.js:312:12)
error	03-Jun-2015 15:44:19	  at Module.require (module.js:364:17)
error	03-Jun-2015 15:44:19	  at require (module.js:380:17)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/build.coffee:13:16)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/build.coffee:1:1)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.loadFile (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
error	03-Jun-2015 15:44:19	  at Module.load (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
error	03-Jun-2015 15:44:19	  at Function.Module._load (module.js:312:12)
error	03-Jun-2015 15:44:19	  at Module.require (module.js:364:17)
error	03-Jun-2015 15:44:19	  at require (module.js:380:17)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/production-build.coffee:2:9)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/scripts/production-build.coffee:1:1)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.exports.run (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/coffee-script.js:119:23)
error	03-Jun-2015 15:44:19	  at compileScript (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/command.js:208:29)
error	03-Jun-2015 15:44:19	  at compilePath (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/command.js:161:14)
error	03-Jun-2015 15:44:19	  at Object.exports.run (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/lib/coffee-script/command.js:96:21)
error	03-Jun-2015 15:44:19	  at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/node_modules/coffee-script/bin/coffee:7:41)
error	03-Jun-2015 15:44:19	  at Module._compile (module.js:456:26)
error	03-Jun-2015 15:44:19	  at Object.Module._extensions..js (module.js:474:10)
error	03-Jun-2015 15:44:19	  at Module.load (module.js:356:32)
error	03-Jun-2015 15:44:19	  at Function.Module._load (module.js:312:12)
error	03-Jun-2015 15:44:19	  at Function.Module.runMain (module.js:497:10)
error	03-Jun-2015 15:44:19	  at startup (node.js:119:16)
error	03-Jun-2015 15:44:19	  at node.js:929:3
error	03-Jun-2015 15:44:19	
error	03-Jun-2015 15:44:19	
error	03-Jun-2015 15:44:19	npm ERR! Linux 3.16.0-25-generic
error	03-Jun-2015 15:44:19	npm ERR! argv "node" "/opt/node-0.10/bin/npm" "run" "build"
error	03-Jun-2015 15:44:19	npm ERR! node v0.10.35
error	03-Jun-2015 15:44:19	npm ERR! npm  v2.6.1
error	03-Jun-2015 15:44:19	npm ERR! code ELIFECYCLE
error	03-Jun-2015 15:44:19	npm ERR! yw2@0.0.0 build: `webpack && coffee scripts/production-build.coffee`
error	03-Jun-2015 15:44:19	npm ERR! Exit status 1
error	03-Jun-2015 15:44:19	npm ERR! 
error	03-Jun-2015 15:44:19	npm ERR! Failed at the yw2@0.0.0 build script 'webpack && coffee scripts/production-build.coffee'.
error	03-Jun-2015 15:44:19	npm ERR! This is most likely a problem with the yw2 package,
error	03-Jun-2015 15:44:19	npm ERR! not with npm itself.
error	03-Jun-2015 15:44:19	npm ERR! Tell the author that this fails on your system:
error	03-Jun-2015 15:44:19	npm ERR!     webpack && coffee scripts/production-build.coffee
error	03-Jun-2015 15:44:19	npm ERR! You can get their info via:
error	03-Jun-2015 15:44:19	npm ERR!     npm owner ls yw2
error	03-Jun-2015 15:44:19	npm ERR! There is likely additional logging output above.
error	03-Jun-2015 15:44:19	
error	03-Jun-2015 15:44:19	npm ERR! Please include the following file with any support request:
error	03-Jun-2015 15:44:19	npm ERR!     /home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/npm-debug.log
simple	03-Jun-2015 15:44:19	Failing task since return code of [/opt/node-0.10/bin/npm run build] was 1 while expected 0
simple	03-Jun-2015 15:44:19	Finished task 'Run Build!' with result: Failed
simple	03-Jun-2015 15:44:19	Running post build plugin 'Docker Container Cleanup'
simple	03-Jun-2015 15:44:19	Running post build plugin 'NCover Results Collector'
simple	03-Jun-2015 15:44:19	Running post build plugin 'Clover Results Collector'
simple	03-Jun-2015 15:44:19	Running post build plugin 'npm Cache Cleanup'
simple	03-Jun-2015 15:44:19	Running post build plugin 'Artifact Copier'
simple	03-Jun-2015 15:44:19	Publishing an artifact: YW2 Website
error	03-Jun-2015 15:44:19	Unable to publish artifact [YW2 Website]: the source directory /home/bamboo/bamboo-agent-home/xml-data/build-dir/YW-YW-JOB1/dist does not exist.
simple	03-Jun-2015 15:44:19	Finished publishing of artifact Shared artifact: [YW2 Website], pattern: [**/*.*] anchored at: [dist] in 0s
simple	03-Jun-2015 15:44:19	Finalising the build...
simple	03-Jun-2015 15:44:19	Stopping timer.
simple	03-Jun-2015 15:44:19	Build YW-YW-JOB1-52 completed.
simple	03-Jun-2015 15:44:20	Running on server: post build plugin 'Clover Delta Calculator'
simple	03-Jun-2015 15:44:20	Running on server: post build plugin 'Build Hanging Detection Configuration'
simple	03-Jun-2015 15:44:20	Running on server: post build plugin 'NCover Results Collector'
simple	03-Jun-2015 15:44:20	Running on server: post build plugin 'Maven Dependencies Postprocessor'
simple	03-Jun-2015 15:44:20	All post build plugins have finished
simple	03-Jun-2015 15:44:20	Generating build results summary...
simple	03-Jun-2015 15:44:20	Saving build results to disk...
simple	03-Jun-2015 15:44:20	Logging substituted variables...
simple	03-Jun-2015 15:44:20	Indexing build results...
simple	03-Jun-2015 15:44:20	Finished building YW-YW-JOB1-52.
```

**Comment by erwan** [comment]
sorry for that, I fix it immediately.
